### ISSUE TITLE
TETRA mode

### ISSUE THREAD

**Issue by joannesberndt** [arancormonk/dsd-neo#1]
Where did your fork version of DSD-FME disappear? Could you add TETRA mode decoding?

**Comment by romanremus** [comment]
Hello arancormonk, and congratulations for the code, it is superb, I have the latest version but in the Ncurses terminal SNR does not look exactly like it does in the code, do you have any idea? I have attached a picture

**Comment by romanremus** [comment]
![Image](https://github.com/user-attachments/assets/c3f8d548-6bf8-49b2-a988-d0fb6d2ceee7)

**Comment by romanremus** [comment]
I think this symbol would work best with SNR, displaying a level, what do you think?

**Comment by romanremus** [comment]
![Image](https://github.com/user-attachments/assets/85fd0044-11b2-4cf9-8ed9-6eeee087e823)

**Comment by romanremus** [comment]
I honestly don't understand how it works or how it displays the SNR, shouldn't it increase from a small line to the largest line as a function of the signal strength when it receives a signal?

**Comment by arancormonk** [comment]
> Hello, Have you started adding TETRA code in dsd-neo? because I look at the source code and I don't see anything.

there's no TETRA for 4000+ miles from where i am... so it'll be a long term goal. there is already good work being done in other open source projects, so when i have the free time and RF captures of TETRA i can start to work on it.

**Comment by M810192** [comment]
I can receive two different tetra networks, so I could provide you with captures. Just tell me what you need and I will try to get it

**Comment by Saqibjaved25** [comment]
I downloaded window version and run the exe, dsd-neo.exe, then set all the required things but when i transmit the signal from my DMR, the software doesn't show anything nor any error or something.

<img width="1141" height="665" alt="Image" src="https://github.com/user-attachments/assets/b19e063f-7c1d-4500-8c1f-249d1edac042" />

**Comment by arancormonk** [comment]
@Saqibjaved25  yea, that ppm is extreme! 100!? can you use sdr# or sdrpp first to determine what the sane values of your rtl dongle should be? use a known good carrier e.g. NOAA if you're in the US.

also, i'd recommend starting a new conversation as a github discussion so as to not continue polluting this issue: https://github.com/arancormonk/dsd-neo/discussions... this has nothing to do with TETRA

**Comment by ysamouhos** [comment]
Hello, 

I am uploading some Tetra DMO (simplex) IQ unencrypted capture and I can upload complex Tetra IQ mixed encypted and unencrypted samples if needed as well. 

[tetradmo_iq.zip](https://github.com/user-attachments/files/31332501/tetradmo_iq.zip)

**Comment by haoyunZhou** [comment]
I've integrated TETRA support into my fork and spent quite a bit of time working on it. I'm not sure about the best way to submit these changes upstream. Would you prefer a single pull request, or should I split the TETRA implementation into several smaller PRs?

**Comment by romanremus** [comment]
haoyunZhou :  What do you think about the TETRA encryption methods? Could they be added ? 
https://github.com/MidnightBlueLabs/TETRA_crypto
https://github.com/MidnightBlueLabs/TETRA_etee
https://github.com/osmocom/osmo-tetra

**Comment by romanremus** [comment]
It decodes in real time; how do you start it for TETRA decoding?

**Comment by arancormonk** [comment]
> I've integrated TETRA support into my fork and spent quite a bit of time working on it. I'm not sure about the best way to submit these changes upstream. Would you prefer a single pull request, or should I split the TETRA implementation into several smaller PRs?

Wow, sure! Smaller PRs would be much easier for me to review if it isn't too much trouble, I'll leave it at your discretion.

**Comment by romanremus** [comment]
Hi, I tried using this command, but the bandwidth shows 48 instead of 72, and it’s not decoding anything; am I doing something wrong during startup? 
dsd-neo.exe -fT -i rtl:0:390.163M:10:-5:72:0:2 -o pulse -N -Z

**Comment by ysamouhos** [comment]
Is there a branch we can test ?

---
There are errors in [haoyunZhou]'s fork

dsd-neo/src/protocol/tetra/osmo_sources/tetra_conv_enc.c:215:29: warning: ‘enum tetra_rcpc_puncturer’ declared inside parameter list will not be visible outside of this definition or declaration
  215 | int get_punctured_rate(enum tetra_rcpc_puncturer pu, uint8_t *in, int len, uint8_t *out)
      |                             ^~~~~~~~~~~~~~~~~~~~
/home/ysam/dsd-neo/src/protocol/tetra/osmo_sources/tetra_conv_enc.c:215:50: error: parameter 1 (‘pu’) has incomplete type
  215 | int get_punctured_rate(enum tetra_rcpc_puncturer pu, uint8_t *in, int len, uint8_t *out)
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/ysam/dsd-neo/src/protocol/tetra/osmo_sources/tetra_conv_enc.c:240:29: warning: ‘enum tetra_rcpc_puncturer’ declared inside parameter list will not be visible outside of this definition or declaration
  240 | int tetra_rcpc_depunct(enum tetra_rcpc_puncturer pu, const uint8_t *in, int len, uint8_t *out)
      |                             ^~~~~~~~~~~~~~~~~~~~
/home/ysam/dsd-neo/src/protocol/tetra/osmo_sources/tetra_conv_enc.c:240:50: error: parameter 1 (‘pu’) has incomplete type
  240 | int tetra_rcpc_depunct(enum tetra_rcpc_puncturer pu, const uint8_t *in, int len, uint8_t *out)
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/ysam/dsd-neo/src/protocol/tetra/osmo_sources/tetra_conv_enc.c:268:35: error: field ‘punct’ has incomplete type
  268 |         enum tetra_rcpc_puncturer punct;

**Comment by romanremus** [comment]
Hi, try https://github.com/haoyunZhou/dsd-neo/tree/main

**Comment by ysamouhos** [comment]
same errors
Am I missing something ?

**Comment by romanremus** [comment]
I managed to compile the code using Visual Studio, but I had to modify it to support BW72; I also created a batch file in the build folder where I set a frequency, and it seems to be decoding, though I'm not seeing any messages in the terminal.

**Comment by ysamouhos** [comment]
Well I am running in Linux ubuntu noble (24.04.4)

ok fixed the issues, so I will test now

**Comment by ysamouhos** [comment]
Hmm it does not decode anything. (I mean unencrypted voice)

**Comment by romanremus** [comment]
Well, I don't know what to say; it decodes for me, but nothing shows up in the Ncurses terminal. As for the voice, I think all the networks here are encrypted; the issue I had with decoding was that it only accepted a maximum bandwidth of 48, not 72.

**Comment by haoyunZhou** [comment]
I’ve pushed a few more changes, including several fixes to the TETRA voice path, RTL bandwidth handling, and demod configuration.
TETRA voice (dbfceb8d). An NTS1 burst is treated as a single 432-bit logical channel. Block 1 and Block 2 are now descrambled using one continuous LFSR run. If the block passes the SCH/F CRC check (interleaver a=103, rate 2/3), it is treated as signalling and is not passed to the speech vocoder. Only blocks that fail the CRC check are treated as TCH/FS.

NTS2 is not treated as speech. It is handled as an inverted NTS1 alias, while polarity is still determined solely from the synchronization burst.

Block 1 consists of the 108 dibits at symbol ages 18..125, following the 7-dibit AACH half.

The ETSI ACELP codec is not included in the repository and is not built by the top-level CMake project. tools/tetra/acelp_adapter is provided as a separate utility. Developers can point -DETSI_TETRA_C_CODE to their local ETSI C-CODE directory and select the resulting adapter through TETRA_VOCODER_CMD.

On Linux and macOS, the command is launched using sh -c; on Windows, it is launched using cmd.exe /C. The pipe protocol sends 137 bytes per speech frame to the vocoder and receives 480 bytes of PCM16LE audio.

RTL (0fc02781). Engine startup now accepts a 72 kHz RTL bandwidth. Previously, the fallback was limited to 48 kHz, causing configurations such as rtl:...:72:... to be rejected.

Config (4942176f). An explicit demodulator lock in auto mode is now preserved only when the saved configuration is actually dPMR. The previous check relied on opts->frame_dpmr, which could incorrectly force dPMR demodulation when another mode was selected.

**Comment by romanremus** [comment]
HaoyunZhou : Is it possible to have all the TETRA decoding messages displayed in the dsd-neo Terminal (-N)? What are your thoughts on the encryption codes? Thanks a lot for the TETRA support in dsd-neo, though I think all the networks here are encrypted.

**Comment by ysamouhos** [comment]
@haoyunZhou Please add support for linux of how we should build the acelp coded and how the chain should run

**Comment by ysamouhos** [comment]
...for example filesnames in linux ARE case snesitive. 

dsd-neo/third_party/tetra_acelp/C-CODE/SDEC_TET.C:18:10: fatal error: source.h: No such file or directory
   18 | #include "source.h"

**Comment by ysamouhos** [comment]
Anyway still not able to hear any unencrypted voice.. 

pipeline is sending 48Khz iq to localhost tcp:41439 and expects voice output to udp:40420 
dsd-neo -i tcp:127.0.0.1:41439 -o udp:127.0.0.1:40420 -fT -Z

Even though env variable is declare -x TETRA_VOCODER_CMD="/usr/local/bin/tetra-acelp-adapter" I do not see it running at anypoint.
